# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.PositiveSmallIntegerField(choices=[(0, 'Olea africana'), (1, 'Moringa'), (2, 'Dovyalis caffra'), (3, 'Croton megalocarpus'), (4, 'Syzygium guineense'), (5, 'Vitex keniensis'), (6, 'Tamarindus indica'), (7, 'Juniperus procera')], default=1)),
                ('gps_n', models.CharField(blank=True, max_length=15, null=True)),
                ('gps_e', models.CharField(blank=True, max_length=15, null=True)),
                ('caretaker', models.CharField(blank=True, max_length=60, null=True)),
                ('water_seasonality', models.BooleanField(default=True)),
                ('water_distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='people.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Planting'), (3, 'Monitoring')], default=1)),
                ('alive', models.BooleanField(default=True)),
                ('reason_dead', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'animals'), (2, 'moved')], null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diameter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='root crown diameter')),
                ('vitality', models.CharField(max_length=100)),
                ('mound', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'gone'), (1, 'severely eroded'), (2, 'eroded'), (3, 'partially eroded'), (4, 'good')], null=True, verbose_name='mound quality')),
                ('fence', models.CharField(blank=True, max_length=140, null=True, verbose_name='fence quality')),
                ('trench', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'gone'), (1, 'severely eroded'), (2, 'eroded'), (3, 'partially eroded'), (4, 'good')], null=True, verbose_name='trench quality')),
                ('irrigated', models.BooleanField(default=True, verbose_name='bottle irrigation clear?')),
            ],
        ),
    ]
