# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_auto_20170223_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='vitality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
