# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_tree_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Syzygium guineense'), (1, b'Juniperus procera'), (2, b'Tamarindus indica'), (3, b'Vitex keniensis'), (4, b'Dovyalis caffra'), (5, b'Olea africana'), (6, b'Moringa'), (7, b'Croton megalocarpus')], default=1),
        ),
        migrations.AlterField(
            model_name='tree',
            name='water_distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
