# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('moves', models.BooleanField(default=False, verbose_name='moves in dry season')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='level of engagement with SFK')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_family', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.BooleanField(default=False)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('flag', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Red'), (2, 'Green'), (3, 'Blue')], null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='people.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.PositiveSmallIntegerField(choices=[(1, 'Parent'), (2, 'Sibling'), (3, 'Spouse')])),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='people.Person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='relative',
            field=models.ManyToManyField(through='people.Relationship', to='people.Person'),
        ),
    ]
