# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='person',
            name='mapping_date',
            field=models.DateField(blank=True, null=True, verbose_name='resource mapping'),
        ),
        migrations.AddField(
            model_name='person',
            name='nrm_date',
            field=models.DateField(blank=True, null=True, verbose_name='NRM mapping'),
        ),
        migrations.AddField(
            model_name='person',
            name='training_date_w',
            field=models.DateField(blank=True, null=True, verbose_name='water conservation training'),
        ),
        migrations.AddField(
            model_name='person',
            name='village',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='village',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
