# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170222_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='demos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='training_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
