# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170222_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relative',
            field=models.ManyToManyField(related_name='relatives', through='people.Relationship', to='people.Person'),
        ),
    ]
